### ISSUE TITLE
install mapMaker 

### ISSUE THREAD

**Issue by Jaip2018** [adeckmyn/mapMaker#1]
Dear Adeckymn , 

How to install the package the mapMaker?

**Comment by adeckmyn** [comment]
- First of all, the package is only useful if you really need to adapt a map into the rather outdated binary format used by the "maps" package.
- You don't mention what operating system you are running. I have only ever run this package under linux. It contains C code, so requires compilation.
- To install it, you can either clone the repository and install manually (easy on linux, but probably less easy on windows). Or you can install the package "devtools" from CRAN and use install_github(). There is no pre-compiled windows version, and I don't intend to make one.
- Also note that this package contains hardly any documentation (except for some comments in the source code).
